### ISSUE TITLE
[Bug]: Using Keybind for Demand Stats requires using it twice

### ISSUE THREAD

**Issue by Wulfbane** [colindm/SubwayBuilderIssues#490]
### Bug Description

When using the Ctrl + 3 Keybind to swap into Demand Stats from any other menu will momentarily switch to demand stats, then close all menus. Upon a second Ctrl + 3 keybind press demand stats will open up correctly. The other 3 menus (Ctrl + 1, 2, 4) do not have this behavior.

Opening Demand Stats from No menus open opens correctly on 1 Ctrl + 3 press. It is only when switching from any of the other 3 menus TO demand stats that this occurs.

### Steps to Reproduce

1. Press Ctrl + 1/2/4 to open a menu other than demand Stats.
2. Press Ctrl + 3 to open demand stats.
3. Demand Stats will momentarily open, then close itself.
4. Press Ctrl + 3 to reopen demand stats.
5. Demand Stats will open correctly.

### Expected Behavior

Switching from Demand Stats from any other menu using the Ctrl + 3 keybind should open demand stats without automatically closing it.

### Operating System

Windows 10

### Game Version

0.8.0

### Save File

[Demand_Stat_Bug.json](https://github.com/user-attachments/files/23565554/Demand_Stat_Bug.json)

Attached completely empty save, occurs on start.

**Comment by Wulfbane** [comment]
Just also realized the Demand Stats menu icon at the bottom of the screen does not consistently the blue "selected" icon when it is opened using the Ctrl + 3 keybind. When swapping menus it may temporarily appear blue, but reset back to its unselected state. (This may be a separate bug, not sure)

**Comment by colindm** [comment]
Fixed in 0.9.0, thanks for letting me know.

**Comment by Wulfbane** [comment]
Hey @colindm, Using v0.9.0, the Ctrl+3 keybind is not fixed. If you use the alternate "M" keybind it works fine. This may still be an open issue.

Incase it is useful/relevant, it should also be noted that every time the "m" key is pressed it will attempt to redraw the demand stats. If demand stats is already open it flashes off then on.
